# Aplicación de matrices de peso

## Matrices de peso y función de activación

In [2]:
import math
import numpy as np
import seaborn as sns

In [17]:
W1= np.array([
    [4.50555331070533,8.84975109553527],
    [-0.279233670126038,2.48555577234568],
    [6.49751252187055,0.333892581828887],
    [-4.06772398638978,-4.06353644199865],
    [-15.4250987980985,-3.43892839136922]
])

In [18]:
W2= np.array([
    [1.97089342975077,3.937778739093,13.4405827732418],
    [-2.88101579550803,-2.34196787325737,13.9839628560371],
    [-0.152977396143684,-2.29171152237197,-27.6844598920285]
])

In [19]:
W3 = np.array([
    [1.39972913113099,0.167010604087305,-0.581985074010472],
    [-1.84349574107304,0.424258914331342,1.09537197434038],
    [0.219031616961889,0.544924498834296,-0.424185312114039],
    [0.00175469379954603,-1.04963923213486,1.0148745237987]
    ])

In [21]:
def f_act(X):
    activada = np.array([1/(1 + np.exp(-x)) for x in X], dtype = np.float64)
    return activada

In [11]:
iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [15]:
xcols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
especie = iris['species'].unique()

In [16]:
X = iris[xcols].copy()
X.insert(0, 'bias', 1)
X

     bias  sepal_length  sepal_width  petal_length  petal_width
0       1           5.1          3.5           1.4          0.2
1       1           4.9          3.0           1.4          0.2
2       1           4.7          3.2           1.3          0.2
3       1           4.6          3.1           1.5          0.2
4       1           5.0          3.6           1.4          0.2
..    ...           ...          ...           ...          ...
145     1           6.7          3.0           5.2          2.3
146     1           6.3          2.5           5.0          1.9
147     1           6.5          3.0           5.2          2.0
148     1           6.2          3.4           5.4          2.3
149     1           5.9          3.0           5.1          1.8

[150 rows x 5 columns]

# Prediccion

In [23]:
prediccion = []
for index, fila in X.iterrows():
    capa1 = f_act(fila.dot(W1))
    capa1 = np.insert(capa1, 0, 1)
    capa2 = f_act(capa1.dot(W2))
    capa2 = np.insert(capa2, 0, 1)

    salida = f_act(capa2.dot(W3))

    prediccion.append(especie[np.argmax(salida)])

In [24]:
prediccion

['setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'virginica',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica',
 'virginica']

In [27]:
iris['Prediccion'] = prediccion

In [28]:
erroneas = iris[iris['species'] != iris['Prediccion']]
erroneas

,sepal_length,sepal_width,petal_length,petal_width,species,Prediccion
70,5.9,3.2,4.8,1.8,versicolor,virginica
83,6.0,2.7,5.1,1.6,versicolor,virginica
84,5.4,3.0,4.5,1.5,versicolor,virginica

In [29]:
eficiencia = (1 - len(erroneas)/len(iris))*100
eficiencia

98.0